<a href="https://colab.research.google.com/github/rohitagarwal6367/Python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.array([1,3,45,55,])

array([ 1,  3, 45, 55])

In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
df = pd.DataFrame(data=np.arange(0, 20).reshape(5, 4),
                  index=["Row1", "Row2", "Row3", "Row4", "Row5"],
                  columns=["Column1", "Column2", "Column3", "Column4"])

In [ ]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.head()  #top 5 record

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.tail(3)     #last 5 record

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.info()    # say the type  of column

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [ ]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
# Indexing
# columnname ,   rowindex[loc], rowindex columnindex number[.iloc]
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
# by using  colummn name
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int64

In [ ]:
df[['Column1', 'Column2']]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [ ]:
# by using rowindex name Loc
df.loc[['Row1','Row2']]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [ ]:
type(df.loc['Row1'])

pandas.core.series.Series

In [ ]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

from matplotlib import pyplot as plt
_df_0['Column1'].plot(kind='hist', bins=20, title='Column1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Column2'].plot(kind='hist', bins=20, title='Column2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2.plot(kind='scatter', x='Column1', y='Column2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Column1']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Column1'}, axis=1)
              .sort_values('Column1', ascending=True))
  xs = counted['Column1']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_3.sort_values('Column1', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Column1')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Column2']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Column2'}, axis=1)
              .sort_values('Column2', ascending=True))
  xs = counted['Column2']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_4.sort_values('Column2', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Column2')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_5['Column1'].plot(kind='line', figsize=(8, 4), title='Column1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_6['Column2'].plot(kind='line', figsize=(8, 4), title='Column2')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df.iloc[2:,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [ ]:
df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
# convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [ ]:
# Basic Operator
df.isnull()

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [ ]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [ ]:
df = pd.DataFrame(data=[[1,np.nan,3],[1,4,5]],
                  index=["Row1", "Row2",],
                  columns=["Column1", "Column2", "Column3"])

In [ ]:
df

Column1  Column2  Column3
Row1        1      NaN        3
Row2        1      4.0        5

In [ ]:
df.isnull().sum()

Unnamed: 0    0
Column1       0
Column2       1
Column3       0
dtype: int64

In [ ]:
df.isnull().sum()==0

Unnamed: 0     True
Column1        True
Column2       False
Column3        True
dtype: bool

In [ ]:
df['Column3'].value_counts()

Column3
3    1
5    1
Name: count, dtype: int64

In [ ]:
df


Unnamed: 0  Column1  Column2  Column3
0       Row1        1      NaN        3
1       Row2        1      4.0        5

In [ ]:
df['Column3'].unique()

array([3, 5])

In [ ]:
#  Reading different data sources with the help of pandas
from io import StringIO

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/student_marks.csv")
df

Name  Math  Science  English  History  Unnamed: 5  Unnamed: 6
0    Laksh    79       37       70       58         NaN         NaN
1   Gaurav    82       86       65       62         NaN         NaN
2    Kabir    99       67       64       64         NaN         NaN
3   Kartik    44       89       68       68         NaN         NaN
4    Harsh    56       35       53       88         NaN         NaN
..     ...   ...      ...      ...      ...         ...         ...
95  Garima   100       70       65       73         NaN         NaN
96   Karan    71       75       89       88         NaN         NaN
97  Aparna    45       71       60       78         NaN         NaN
98    Jaya    78       83       55       42         NaN         NaN
99   Tejas    46       60       92      100         NaN         NaN

[100 rows x 7 columns]

In [ ]:
df

Name  Math  Science  English  History  Unnamed: 5  Unnamed: 6
0    Laksh    79       37       70       58         NaN         NaN
1   Gaurav    82       86       65       62         NaN         NaN
2    Kabir    99       67       64       64         NaN         NaN
3   Kartik    44       89       68       68         NaN         NaN
4    Harsh    56       35       53       88         NaN         NaN
..     ...   ...      ...      ...      ...         ...         ...
95  Garima   100       70       65       73         NaN         NaN
96   Karan    71       75       89       88         NaN         NaN
97  Aparna    45       71       60       78         NaN         NaN
98    Jaya    78       83       55       42         NaN         NaN
99   Tejas    46       60       92      100         NaN         NaN

[100 rows x 7 columns]

In [ ]:
df = pd.read_csv("/content/student_marks.csv")

In [ ]:
df

Name  Math  Science  English  History  Unnamed: 5  Unnamed: 6
0    Laksh    79       37       70       58         NaN         NaN
1   Gaurav    82       86       65       62         NaN         NaN
2    Kabir    99       67       64       64         NaN         NaN
3   Kartik    44       89       68       68         NaN         NaN
4    Harsh    56       35       53       88         NaN         NaN
..     ...   ...      ...      ...      ...         ...         ...
95  Garima   100       70       65       73         NaN         NaN
96   Karan    71       75       89       88         NaN         NaN
97  Aparna    45       71       60       78         NaN         NaN
98    Jaya    78       83       55       42         NaN         NaN
99   Tejas    46       60       92      100         NaN         NaN

[100 rows x 7 columns]

In [ ]:
data=('col1,col2,col3\n',
 'x,y,1\n',
 'a,b,2\n',
 'c,d,3')

In [ ]:
type(data)

tuple

In [ ]:
# in memory file formate object
StringIO(data)

TypeError: initial_value must be str or None, not tuple

In [ ]:
import pandas as pd


In [ ]:
html=pd.read_html("https://en.wikipedia.org/wiki/Mobile_country_code#National_operators")

In [ ]:
type(html)

list

In [ ]:
html   # All tables

[   MCC  MNC Brand      Operator       Status Bands (MHz)  \
 0    1    1  TEST  Test network  Operational         any   
 1    1    1  TEST  Test network  Operational         any   
 2  999   99   NaN  Internal use  Operational         any   
 3  999  999   NaN  Internal use  Operational         any   
 
                               References and notes  
 0                                              NaN  
 1                                              NaN  
 2  Internal use in private networks, no roaming[6]  
 3  Internal use in private networks, no roaming[6]  ,
      Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB   
 1                    412                                Afghanistan       AF   
 2                    276                                    Albania       AL   
 3                    603                                    Algeria       DZ   
 4               

In [ ]:
html[0]

MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any   
1    1    1  TEST  Test network  Operational         any   
2  999   99   NaN  Internal use  Operational         any   
3  999  999   NaN  Internal use  Operational         any   

                              References and notes  
0                                              NaN  
1                                              NaN  
2  Internal use in private networks, no roaming[6]  
3  Internal use in private networks, no roaming[6]

In [ ]:
html=pd.read_html("https://en.wikipedia.org/wiki/Economy_of_the_United_States", match="GDP per capita")

In [ ]:
html[0]

0  \
0   New York City, the world's principal fintech a...   
1                                            Currency   
2                                         Fiscal year   
3                                 Trade organizations   
4                                       Country group   
5                                          Statistics   
6                                          Population   
7                                                 GDP   
8                                            GDP rank   
9                                          GDP growth   
10                                     GDP per capita   
11                                GDP per capita rank   
12                                      GDP by sector   
13                                   GDP by component   
14                                    Inflation (CPI)   
15                      Population below poverty line   
16                                   Gini coefficient   
17                            Human Development Index   
18                       Corruption Perceptions Index   
19                                        Labor force   
20                          Labor force by occupation   
21                                       Unemployment   
22                               Average gross salary   
23                                 Average net salary   
24                      Final consumption expenditure   
25                            Gross capital formation   
26                                        Yield curve   
27                         Purchasing Managers' Index   
28                                    Main industries   
29                                           External   
30                                            Exports   
31                                       Export goods   
32                               Main export partners   
33                                            Imports   
34                                       Import goods   
35                               Main import partners   
36                                          FDI stock   
37                                    Current account   
38                                Gross external debt   
39                                    Public finances   
40                                    Government debt   
41                                     Budget balance   
42                                           Revenues   
43                                           Expenses   
44                                       Economic aid   
45                                      Credit rating   
46                                   Foreign reserves   
47  All values, unless otherwise stated, are in US...   

                                                    1  
0   New York City, the world's principal fintech a...  
1          United States dollar (USD) US Dollar Index  
2                            October 1 – September 30  
3         WTO, G-20, G7, OECD, USMCA, APEC and others  
4   Advanced economy[5] High-income economy[6] Wel...  
5                                          Statistics  
6                    340,332,281 (August 30, 2023)[9]  
7   $28.78 trillion (nominal; 2024)[10]  $28.78 tr...  
8                 1st (nominal; 2024) 2nd (PPP; 2024)  
9     2.1% (2022)[11] 2.5% (2023)[11] 2.7% (2024)[11]  
10  $85,373 (nominal; 2024)[10]  $85,373 (PPP; 202...  
11                6th (nominal; 2024) 8th (PPP; 2024)  
12  Agriculture: 0.9% Industry: 18.9% Services: 80...  
13  Household consumption: 67.9% Government consum...  
14                                      3% (2023)[14]  
15          11.5% (2022)[15]  37.9 million (2022)[15]  
16  46.7 high (2022, USCB)[16] 41.7 medium (2020, ...  
17  0.927 very high (2022)[18] (20th)  0.823 very ...  
18        69 out of 100 points (2023)[19] (rank 24th)  
19  161,200,000 (2023)[20] 62.4% employment rate (...  
20  Agriculture: 1.0% Industry: 19% Services: 80% ...  
21  4.1% (September 2024)[

In [ ]:
html[0].to_html('/content/index.html')

In [ ]:
html

[                                                    0  \
 0   New York City, the world's principal fintech a...   
 1                                            Currency   
 2                                         Fiscal year   
 3                                 Trade organizations   
 4                                       Country group   
 5                                          Statistics   
 6                                          Population   
 7                                                 GDP   
 8                                            GDP rank   
 9                                          GDP growth   
 10                                     GDP per capita   
 11                                GDP per capita rank   
 12                                      GDP by sector   
 13                                   GDP by component   
 14                                    Inflation (CPI)   
 15                      Population below poverty line   
 16           