<a href="https://colab.research.google.com/github/rohitagarwal6367/Python/blob/main/VAC_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

python is high level, general purpose, iterpreted programming language which was invented in 1991 by guido van rossoum

fundamental of python
1. data type
2. variable
3. print() and input()

In [ ]:
type(56)

In [ ]:
type('sam')

In [ ]:
type(5>4)

In [ ]:
# 2. Variable ---> this is a container in which

In [ ]:
a=3
b=4
c=a+b
print(c)

In [ ]:
a='3'
b='4'
c=a+b
print(c)   #string are connected

In [ ]:
#type casting ---> Using type casting, we can change or update one data type to another data type

In [ ]:
a = int(input("Enter first number:"))
b = int(input("Enter second number:"))
c = a+b
print(c)

In [ ]:
# Mostly used operator in python
# # (1): Add(+) ===> 5=3 = 8
# (2) subtractor(-) ===> 7-2 = 5
# (3) Multiplication(*) ==> 5*2 = 10
# (4) Divison(/) ==> 5/2  = 2.5
# (5) floor Division(//) ==> 5/2 = 2
#(6) Module(%) ==> for remainder Calculations ==>25%10 =5(remainder)
#(7) Equal to(=) ==> For value assignment ==> a=5 , b='sum'
#(8) Equal equal to(==) ==> for values comparsion ==> 'sum'== 'raj'
#(9) Not equal to(!=) ==> 4!=5
#(10) grater than (>) ==> 5>4
#(11) less than(<) ==> 4<8
#(12) greater than or equal to (>=) ===> 5>=5
 #(13) less than or equal to (<=) ===> 4<=5
 #(14)Floor Division(//) ----> 5//2 = 2(It will convert values in round figure)

In [ ]:
#Conditional statment in python
# 1) IF
# 2) ELIF
# 3) ELSE

In [ ]:
a= input("Enter name: ")

if( a== 'sam'):
    print('yes')
elif(a=='mohit'):
  print('no')
elif(a=='raj'):
  print('ok')
else:
    print('try again')

In [ ]:
a= int(input("Enter yout age:"))
if(0<=a<=20):
  print('child')
elif(21<=a<=50):
  print('young')
elif(51<=a<=90):
  print('Adult')
else:
  print("Please enter a valid age...")

In [ ]:
# loop in python
# 1. for loop
# 2. while loop

In [ ]:
# 1. for Loop

# Indexing will start from 0 and length start from 1
# It will include starting inndex value and exclude Last index value

In [ ]:
# Write a program who write 1 to 5
for i  in range(1,5):
  print(i)

In [ ]:
# Q(2). Write a program in which step value will be 2 and range of number is 1 to 10
for i in range(1,11):
  print(i)

In [ ]:
for i in range(1,12,2):
  print(i)

In [ ]:
# if a = 'python' then you  have to  print it

In [ ]:
a = 'python'
for i in range(len(a)):
  print(a[i])

In [ ]:
a='python'
for i in range(len(a)):
  print(a[i], end=' ')

2. while loop
a. Initialization
b. Condition
c. Increment

In [ ]:
# Write  a program who print 1 to 4
i = 1 # initialiation
n =  4
while(i<=n):        ## Condition
  print(i)
  i = i+1      ## Increment

In [ ]:
# Q2. Write  a program who will  caculate addition of number in a given range

i = 1
n = 4
sum = 0
while(i<=n):
  sum = sum + i
  i = i + 1
  print("Total Sum = ", sum)
  ### 1 + 2 + 3 + 4 = 10

Q. Positive, Negative, Zero

In [ ]:
a = int(input("Enter the number:"))
if(a>0):
  print("Positive")
elif(a<0):
  print("Negative")
else:
  print("Zero")

Q. Odd, Even

In [ ]:
a = int(input("Enter the number:"))
if(a%2==0):
  print("Even")
else:
  print("odd")

print all even number 1 to 50

In [ ]:
for i in range(2,51,2):
  print(i)

Q. First 10 natural number

In [ ]:
for i in range(1,11):
  print(i)

Q. year is leap or not

In [ ]:
a = int(input("Enter the year:"))
if(a%4==0):
  print("Leap year")
else:
  print("Not a leap year")

Q. Write a program to find the largest of three number

In [ ]:
a = int(input("Enter first number:"))
b = int(input("Enter second number:"))
c = int(input("Enter third number:"))
if(a>b and a>c):
  print("largest",a)
elif(b>a and b>c):
  print("largest",b)
else:
  print("largest",c)

Q. Check whether a character is vowel or consonant

In [ ]:
chr =  input("Enter the character:")
if(chr=='a' or chr=='e' or chr=='i' or chr=='o' or chr=='u'):
  print("Vowel")
else:
  print("Cons")

Q. eligible for vote

In [ ]:
a = int(input("Enter the number:"))
if(a>=18):
  print("Eligible for vote")
else:
  print("Not eligible for vote")

Q. Divisble by 5 or 11

In [ ]:
a =  int(input("Enter the number:"))
if(a%5==0 or a%11==0):
  print("Divisible")
else:
  print("Not divisible")

Q. Palindrome no.

In [ ]:
text = input("Enter the text:")
if(text==text[::-1]):
  print("It is Palindrome")
else:
  print("It is not a palindrome")

In [ ]:
# function in python
# Reusable block of code

# type of function
# 1. Pre-defined function ---> print(), input(), min(), max(), count(),
# 2.

In [ ]:
#  Syntax
#

In [ ]:
# Write a program who add 2 number
def my_add():
  a = 5
  b = 6
  c = a  + b
  print("Add=" ,c)
my_add()

Parameter and Arguments

Parameter ---> these are the value which we passes when wee create function

Arguments ---> These are values  which we passes when we call a function


In [ ]:
def my_add(a,b):
  c = a + b
  print("Total=" ,c)
my_add(3,4)

#  herre (3,4)---> argument,   (a,b)--> parameter

In [ ]:
def oddeve():
  a = int(input("Enter the number:"))
  if(a%2==0):
    print("Even Number")
  else:
    print("odd Number")
oddeve()

In [ ]:
def oddeve(a):
  if(a%2==0):
    print("Even Number...")
  else:
    print("odd Number...")
oddeve(6)


# here(6)---> Arguments, (a) ---> Parameter

In [ ]:
# lambda function ==> a lambda function can take any number of argunment but can have only  one expression
# syntax : lambda argunmment:expression
# Ex 1
x=lambda a:a+5
print("Total value =",x(2))

# Ex 2
x=lambda a,b:a*b
print("Total product is =",x(2,3))

# ex 3.
x=lambda a,b,c:a+b-c
print("Total =",x(2,3,4))

Filter Function ==> The filter function returns on iterator where the items are filtered through a function to test, if the term is accepted return true or false

In [ ]:
ages=[5,12,17,18,34,57,64,50]
def myfunc(x):
  if (x<=18):
    return True
  else:
    return False
kid=list(filter(myfunc,ages))
print(kid)

# print(kid) #output will be in list form
# for x in kid:
#   print(x)

**Map function** ==> The map() executes a specified function for each item in a iterative . The item is sent to the function as parameters

In [ ]:
a =["3","45","89"]

#method -1
# print(a)

for i in range(len(a)):
   a[i] = int(a[i])
print(a)
# a[2] = a[2] + 1
# print(a[2])

#method -2 (by using map function)
b = list(map(int,a))
print(b)
# b [2] = b[2] + 1
# print(b[2])


String in python

1. Indentification- ' ' ," " , ''' '''

2. Immutable data type ---> it is can not update or change values at run time

3. Indexing start from 0 and length start from 1

In [ ]:
a = 'python'
print(a[0])
print(a[1])
print(a[2])
print(a[3])

In [ ]:
a = 'python'
for i in a:
  print(i)

In [ ]:
# Slicing in String (Starting_index value will be include and last value will exclude)
a = 'Python'
print(a[0:4])
print(a[0:])
print(a[:6])
print(a[:])
print(a[-1:-4:-1])

In [ ]:
# Properties of string


In [ ]:
from logging import basicConfig
# 1. Concatenation
a = '12'
b = '34'
c = a + b
c

In [ ]:
# 2. Repplication
a = '12'
a*3

**Function in String**

In [ ]:
#  1. Len() ---> It will return length of a string
a = 'sam'
print(len(a))

In [ ]:
# 2. index() ---> It will return index number of a substring in a string
a = 'sam'
print(a.index('m'))

In [ ]:
# 3. split() --->
a = 'p y t h o n'
a.split(' ')

In [ ]:
# 4. replace() ---> it will replace substring in string
text = "I love python"
print(text)
print(text.replace("python","java"))

In [ ]:
# 5. isdigit() ---> It will return True if digit in a string otherwise it will return False.
a = '1234'
a.isdigit()

In [ ]:
# 7. isalnum() ---> it will return true if
# a. Character are available in stering
# b. only digits are available  in string
# c. both available  in string
# otherwise it will return false


In [ ]:
a= "sam1234"
print(a.isalnum())
a='sam'
print(a.isalnum())
a='1234'
print(a.isalnum())
a=''
print(a.isalnum())

Q. reverse hello

In [ ]:
a =  'hello'
print(a[-1:-6:-1])

In [ ]:
a = 'programming'
print(a[3:7])

Q. count a in banana

In [ ]:
x = 'banana'
x.count("a")

Q. Conver in upper case

In [ ]:
s = 'hello world'
s.upper()

Q. check start from hello

In [ ]:
s = "hello world"
if s.startswith("hello"):
    print("The string starts with 'hello'")
else:
    print("The string does not start with 'hello'")

Q. indexing of in hello world

In [ ]:
s = "hello world"
print(s.index('o'))

Q. split s = "apple,banana,cherry"

In [ ]:
s = "apple, banana, cherry"
s.split(', ')

In [ ]:
a = "abc123"
print(a.isalnum())

In [ ]:
# List in python

# 1. Identification
# 2. Mutable data type ---> we can change or update values at run time
# 3. indexing start from 0 and length start from 1
# 4. Hetrogeneous data type ---> we can store diff diff data type element in the list

In [ ]:
a = ['sam', 'raj',  23,34,45]
type(a)

In [ ]:
# loop in list
for i in range(len(a)):
  print(a[i])

In [ ]:
# Properties of list

In [ ]:
# 1. concatenation
a=[1,2,3]
b=[6,6,7]
c=a+b
c

In [ ]:
# 2. Replication
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
a=[1,2,3]
sum = 0
for i in range(len(a)):
  sum = sum + a[i]
print("total = ",sum)

In [ ]:
a = ['sam', 'raj', 23,43, 34]

In [ ]:
# Function in list
# 1. min() --->

In [ ]:
# append() --> it will add element at the last indexing of list
a = [1,2,3]
print(a)
a.append(55)
print(a)

In [ ]:
a = [1,2,3]
print(a)
a.insert(1,'Rahul')
print(a)

In [ ]:
a = [1,2,3]
print(a)
a.reverse()
print(a)

In [ ]:
# pop() ----> delete element from last indexing

In [ ]:
a = [1,2,3,4]
print(a)
a.pop()
print(a)
a.pop()
print(a)

### **How can we create a user defined list**

In [ ]:
a = []
size = int(input("how many element you want to store"))
for i in range(size):
  val = input("Enter item:")
  a.append(val)
print(a)

In [ ]:
a = []
size = int(input("how many element you want to store"))
for i in range(size):
  val = int(input("Enter item:"))
  a.append(val)
print(a)
sum = 0
for i in range (len(a)):
  sum = sum + a[i]
print("Total=",sum)

**Tuple in python**

In [ ]:
# 1. Identification
# 2. Mutable data type
# 3. indexing start from 0 and length start from 1
# 4. Hetrogeneous data type

In [ ]:
a = ['sam', 'raj', 43, 52, 34]
print(a)

In [ ]:
type(a)

In [ ]:
#  Indexing
print(a[0])
print(b[1])
print(c[2])

In [ ]:
#  loop in tuple
a = ('sam', 'raj', 45, 67.24)
for i in range(len(a)):
  print(a[i], end=" ")

In [ ]:
#  Immutable data type
a = ('sam', 'raj', 45, 67.24)
# a[1] = 'Rahul'
print(a)
b = list(a)
b[1] = 'Rahul'
print(b)
c = tuple(b)
print(c)

Dictionary in Python

In [ ]:
#  Identification = {key:value, key:value}

In [ ]:
a={'Brand':'Kia', 'Model':'Seltos','Year': 2025 }
print(a)
type(a)

In [ ]:
### Loop in dictionary

In [ ]:
for i in a:
  print(i)

In [ ]:
for i in a.keys():
  print(i)

In [ ]:
for i in a:
  print([a])

In [ ]:
import numpy as np


**One Dimensional Array**

In [ ]:
import numpy as np
a = [1,2,4,5]
b = np.array(a)
b

array([1, 2, 4, 5])

In [ ]:
a=[]
size=int(input("enter size"))
for i in range(size):
  val=int(input("enter number"))
  a.append(val)
print(a)
b=np.array(a)
b

enter size3
enter number5
enter number4
enter number6
[5, 4, 6]


array([5, 4, 6])

In [ ]:
import numpy as np


In [ ]:
a = [[1,2,3], [2,5,7], [8,9,5]]
b = np.array(a)
b

array([[1, 2, 3],
       [2, 5, 7],
       [8, 9, 5]])

In [ ]:
print("Total Shape =",b.shape) ## shape = n(rows), n(column)
print("Total Element = ",b.size) ## shape = n(rows) * n(column)
print("Total  dimension=",b.ndim) ## dimension = 2(x,y)

Total Shape = (3,)
Total Element =  3
Total  dimension= 1


**Pre defined function in numpy**

In [ ]:
#(1). zeroes()---> It will create an array in which all the values will be
# 0 i either one dimension or multi-dimension.

In [ ]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 2. ones() ---> It will create an array in which all the value will be 1

In [ ]:
a = np.ones(3)
a

array([1., 1., 1.])

In [ ]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 3. eye() --> it will create an array in which digonal positional element will be one and rest all are 0

In [ ]:
a =  np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# 4. diag() ---> it will create an array in which we can add or update our digonal positional element

In [ ]:
a = np.array([1,34,3,47])
a

array([ 1, 34,  3, 47])

In [ ]:
b = np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0,  0, 47]])

In [ ]:
#(1). Randint()---> it will generate random numbers ina given range
# np.random.randint(min,max,total)

In [ ]:
a=np.random.randint(1,10,3)
a

array([8, 5, 9])

In [ ]:
# 2. Rand() ---> it will generate random numbers in range 0  to  1

In [ ]:
a = np.random.rand(3,3)
a

array([[0.34717154, 0.88276426, 0.39465173],
       [0.11895305, 0.61454886, 0.41455243],
       [0.54156598, 0.42871799, 0.15632486]])

In [ ]:
# seed() --> it will fix our random generated data.

In [ ]:
np.random.seed(34)
a = np.random.randint(1,10,3)
a

array([2, 7, 6])

View vs **Copy**

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[2:5]
b[:] = 0
b
a

array([1, 2, 0, 0, 0, 6, 7, 8, 9])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[2:5].copy()
b[:] = 0
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Operations on Array**

In [ ]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
a = np.array([5, 6, 7, 8]).reshape(2,2)
b = np.array([2, 5, 9, 6]).reshape(2,2)
a

array([[5, 6],
       [7, 8]])

In [ ]:
b

array([[2, 5],
       [9, 6]])

In [ ]:
a + b

array([[ 7, 11],
       [16, 14]])

In [ ]:
a**2

array([[25, 36],
       [49, 64]])

In [ ]:
# unique() ---> it will return unique array
# it will return 3 array
# 1. Unique array
# 2. Indexinng of the unique array
# 3. total occurance of unique array

In [ ]:
a = np.array([1,2,2,2,2,4,5,6,8])
np.unique(a,return_index=True, return_counts=True)

(array([1, 2, 4, 5, 6, 8]),
 array([0, 1, 5, 6, 7, 8]),
 array([1, 4, 1, 1, 1, 1]))

**Htack And Vtack**

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([5, 6, 8, 9])
np.hstack((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 8, 9])

In [ ]:
np.vstack((a,b,c))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 8, 9]])

Create an array using numpy

In [ ]:
import numpy as np
a = [1,2,4,5]
b = np.array(a)
b

array([1, 2, 4, 5])

Create an array of 10 random number

In [ ]:
a = np.random.randint(1,20,10)
a

array([ 4,  6, 12, 11, 15, 19,  7,  6,  1,  6])

Create an array of element from 10-20

In [ ]:
a = np.arange(10,20,1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

create an array which contain value 5, 10 time

In [ ]:
a = [5]
a*10

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

6. Create one dimensional and convert into 3*3 matrix

In [ ]:
a = np.array([5, 6, 7, 8, 5, 6, 3, 5, 4]).reshape(3,3)
a


array([[5, 6, 7],
       [8, 5, 6],
       [3, 5, 4]])

Create 2d array range 0 to 1

In [ ]:
a = np.random.rand(3,3)
a

array([[0.6090357 , 0.80799282, 0.82651133],
       [0.27168333, 0.83647644, 0.28254136],
       [0.1383086 , 0.71472027, 0.47253661]])

Q8. 2D array horizontally and vertically

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([5, 6, 8, 9])
np.hstack((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 8, 9])

In [ ]:
np.vstack((a,b,c))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 8, 9]])